#!/usr/bin/env python3

from argparse import ArgumentParser
from utils import retro, parse_dirs

p = ArgumentParser()

p.add_argument('directories', nargs='*',
                help = 'The directories to be processed.')

p.add_argument('--retro', action = 'store_true',
                help = 'Find some illusion of joy in a fallen world.')

args = p.parse_args()

if args.retro:
    retro()
elif args.directories:
    parse_dirs(args.directories)
else:
    p.print_help()
